[package]

name = "azure"
version = "0.1.0"
authors = ["The Servo Project Developers"]

build = "build.rs"

[dependencies]
libc = "*"

[dependencies.geom]
git = "https://github.com/servo/rust-geom"

[dependencies.skia]
git = "https://github.com/servo/skia"

[target.i686-unknown-linux-gnu.dependencies.x11]
version = "1.1.1"
features = ["xlib"]

[target.x86_64-unknown-linux-gnu.dependencies.x11]
version = "1.1.1"
features = ["xlib"]

[target.i686-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.x86_64-unknown-linux-gnu.dependencies.freetype]
git = "https://github.com/servo/rust-freetype"

[target.i686-unknown-linux-gnu.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.x86_64-unknown-linux-gnu.dependencies.freetype-sys]
git = "https://github.com/servo/libfreetype2"

[target.x86_64-apple-darwin.dependencies.core_foundation]
git = "https://github.com/servo/rust-core-foundation"

[target.x86_64-apple-darwin.dependencies.core_graphics]
git = "https://github.com/servo/rust-core-graphics"

[target.x86_64-apple-darwin.dependencies.core_text]
git = "https://github.com/servo/rust-core-text"

[target.arm-linux-androideabi.dependencies.egl]
git = "https://github.com/servo/rust-egl"
